parameters:
  environment: ''
  
jobs:
  - job: Test_${{parameters.environment}}
    steps:
      - task: Docker@2
        displayName: Build docker image and test
        inputs:
          command: 'build'
          Dockerfile: 'Presentation/Postman/Dockerfile'
          arguments: --build-arg ENVIRONMENT="${{parameters.environment}}" --no-cache --progress=plain