    version: '3.4'
    
    services:
      currency:
        image: currency
        container_name: currency-api
        build:
          context: .
          dockerfile: Dockerfile
        ports:
        - 8080:80